Refactor classes
ALEXJAZZ008008/KinectLibraries pull request #9
Opened 2018-07-11 16:46 UTC by ALEXJAZZ008008

Refactored and added point cloud output (raw)

2018-07-14 01:25 UTC, NikEfth requested changes

2018-07-14 01:25 UTC, NikEfth commented on src/KinectFrontend/KinectFrontend.h
> +    inline int ser_kinect_interface_ptr(KinectInterface * kinect_interface_ptr)
typo

2018-07-14 01:25 UTC, NikEfth commented on src/KinectInterface/KinectBackend/KinectBackend.cpp
> +            KinectBackend::getInstance().m_kinect_object_ptr->get_depth().at(j).at(i) =
Could you change this to be a 1D array (or vector)?

2018-07-14 01:25 UTC, NikEfth commented on src/KinectInterface/KinectBackend/KinectBackend.cpp
> +    unsigned short *depth_ptr = (unsigned short *)data;
static_cast

2018-07-14 01:25 UTC, NikEfth commented on src/KinectInterface/KinectBackend/KinectBackend.cpp
> +void KinectBackend::depth_callback(freenect_device *m_freenect_device_ptr, void *data, unsigned int timestamp)
check if empty? or the same?

2018-07-14 01:25 UTC, NikEfth commented on src/KinectInterface/KinectBackend/KinectBackend.cpp
> +    KinectBackend::getInstance().append_depth_message("Received depth frame at " + to_string(timestamp) + "\n");
Reduce the number of characters.

2018-07-14 01:25 UTC, NikEfth commented on src/KinectInterface/KinectBackend/KinectBackend.cpp
> +    KinectBackend::getInstance().append_depth_message("Received depth frame at " + to_string(timestamp) + "\n");
move at interface

2018-07-14 01:25 UTC, NikEfth commented on src/KinectInterface/KinectBackend/KinectBackend.cpp
> +    KinectBackend::getInstance().append_video_message("Received video frame at "  + to_string(timestamp) + "\n");
same as above

2018-07-14 01:25 UTC, NikEfth commented on src/KinectInterface/KinectBackend/KinectBackend.cpp
> +int KinectBackend::calculate_point_cloud()
move in the point cloud numerics

2018-07-14 01:25 UTC, NikEfth commented on src/KinectInterface/KinectBackend/KinectBackend.cpp
> +            *vector_iterator = (j - (m_kinect_object_ptr->get_resolution().at(1) / 2.0f)) * (m_kinect_object_ptr->get_depth().at(j).at(i) - 10) * 0.0021f;
0.0021f make it a variable. The default value will be set in the constructor. Create a set function

2018-07-14 01:25 UTC, NikEfth commented on src/KinectInterface/KinectBackend/KinectBackend.cpp
> +            *vector_iterator = (j - (m_kinect_object_ptr->get_resolution().at(1) / 2.0f)) * (m_kinect_object_ptr->get_depth().at(j).at(i) - 10) * 0.0021f;
m_kinect_object_ptr->get_resolution().at(1) cast to float

2018-07-14 01:25 UTC, NikEfth commented on src/KinectInterface/KinectBackend/KinectBackend.cpp
> +int KinectBackend::calculate_point_cloud()
If you find the link add it here!

2018-07-14 01:27 UTC, NikEfth commented
I broken the front end into pieces. Now konnector is the class which handles the managerial aspects. Logger prints the log msgs, settings allow you to set option (but are not passed at the backend). 
Your tasked (in addition to those marked here are to implement all the `\todo` I have added in the source code. 
There is commentary to help, but we'll skype tomorrow noon for details.

2018-07-24 16:06 UTC, ALEXJAZZ008008 commented
Please merge me!

2018-07-26 23:56 UTC, merged